" Startup: {{{
if has('vim_starting')
  set all&
  set nocompatible
  mapclear
  mapclear!
endif

let &termencoding = &encoding
set encoding=utf-8
set fileencodings=usc-bom,utf-8,big5,taiwan,chinese,default,latin1
language messages POSIX
filetype plugin indent on
" }}}


" 檔案格式 {{{
set fileformats=unix
set noendofline
" }}}


" 記憶 {{{
set history=600
set viewoptions=folds,cursor
set updatetime=10000
set noswapfile
set directory-=.
set backupdir-=.
set updatecount=0
" }}}


" 排版 {{{
set expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent smartindent smarttab
set shiftround
set cinkeys-=:
set cinoptions+=(0
set textwidth=78
" }}}


" 編輯 {{{
set mouse=nvi
set virtualedit=block
set clipboard=autoselect,exclude:cons\|linux
set tildeop
set backspace=indent,eol,start
set whichwrap=b,s,<,>,[,]
set nojoinspaces
set nrformats=hex
set nostartofline

set scrolloff=10
set sidescrolloff=40
set sidescroll=1
set scrollopt=ver,hor,jump

set timeoutlen=4000
" }}}


" 外觀 {{{
set cursorline
set number
set hlsearch
nohlsearch
set ruler
set showcmd
set shortmess+=I
set nolinebreak
set display=lastline
set listchars=tab:>-,eol:¬,trail:*,extends:»,precedes:«
set background=dark
set ambiwidth=single
syntax on
" }}}


" 尋找、搜尋 {{{
set ignorecase
set smartcase
set incsearch
set matchpairs+=<:>
" }}}


" 自動完成 {{{
set omnifunc=syntaxcomplete#Complete
set pumheight=20
set menuitems=35
set completeopt=longest,menu
set complete+=U
set showfulltag

set wildmenu
set wildmode=longest:full,full
set wildoptions=tagfile
" }}}


" 多檔案編輯 {{{
set splitbelow
set splitright
set noequalalways
set previewheight=9
set switchbuf=useopen,usetab,newtab
set tabpagemax=400
set diffopt+=vertical,context:4,foldcolumn:1
" }}}


" Vim 7.3 / 7.4 {{{
if version >= 703
  set conceallevel=1
  set concealcursor=nc
  set cinoptions+=L0
  if exists('+regexpengine')
    set regexpengine=0
  endif
endif
" }}}


" Finish: {{{
set secure
" }}}

" vim: expandtab softtabstop=2 shiftwidth=2 foldmethod=marker
